trigger:
  branches:
    include: 
      - refs/tags/*

pr: none

variables:
  GitHub.Organization: 'HoeflingSoftware'
  GitHub.Repo: 'DevOps.Templates'

jobs:
- template: GitHub/azure-pipelines.yml
  parameters:
    githubOrganization: '$(GitHub.Organization)'
    githubRepo: '$(GitHub.Repo)'
    githubToken: '$(GitHub.Token)'
    publish: false
